# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Kiryra: header-only target, no brave_component_updater or feature-flag deps.

source_set("common") {
  sources = [ "pref_names.h" ]
  deps = [ "//base" ]
}
