# Copyright 2026 The Kiryra Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("core") {
  sources = [
    "https_upgrade_exceptions_core.cc",
    "https_upgrade_exceptions_core.h",
  ]
  deps = [
    "//base",
    "//url",
  ]
}
